apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1 # In dev, use fewer replicas to save cost
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: NODE_ENV
          value: "development"
